apiVersion: v1
kind: Service
metadata:
    name: "vpn-8656"
    labels:
        app: "vpn-8656"
spec:
    type: LoadBalancer
    ports:
    - port: 30333
      targetPort: 30333
      protocol: TCP
      name: http
    selector:
        app: "vpn-8656"