on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: foxterimages.azurecr.io
        username: ${{ secrets.acr_foxterimages_username }}
        password: ${{ secrets.acr_foxterimages_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t foxterimages.azurecr.io/vpn:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push foxterimages.azurecr.io/vpn:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_vpn_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep vpnadd7 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace vpnadd7`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: vpnadd7
        container-registry-url: foxterimages.azurecr.io
        container-registry-username: ${{ secrets.acr_foxterimages_username }}
        container-registry-password: ${{ secrets.acr_foxterimages_password }}
        secret-name: vpndockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: vpnadd7
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          foxterimages.azurecr.io/vpn:${{ github.sha }}
        imagepullsecrets: |
          vpndockerauth
